name: Flyway Migrate
 
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - terraform
    paths:
      - 'migrations/**'
 
jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      TF_VAR_db_username: ${{ vars.DB_USERNAME }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: af-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Refresh
        working-directory: terraform
        run: terraform refresh

      - name: Get outputs
        uses: dflook/terraform-output@v1
        id: tf-outputs
        with:
          path: terraform

      - run: "# ${{ steps.tf-outputs.outputs.beanbd_db_endpoint }}"
      
      - name: Flyway validate and migrate
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:mysql://${{ steps.tf-outputs.outputs.beanbd_db_endpoint }}/beanbd_db
          user: ${{ vars.DB_USERNAME }}
          password: ${{ secrets.DB_PASSWORD }}
          locations: filesystem:./migrations
        env:
          FLYWAY_VALIDATE_MIGRATION_NAMING: true
 
