name: Flyway Migrate
 
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'migrations/**'
 
jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      TF_VAR_db_username: ${{ vars.DB_USERNAME }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: af-south-1

      - name: Get outputs
        uses: dflook/terraform-output@v1
        id: tf-outputs
        with:
          path: terraform

      - run: "# DB Endpoint: ${{ steps.tf-outputs.outputs.beanbd_db_endpoint }}"

      - name: Install MSSQL Client
        uses: potatoqualitee/mssqlsuite@v1.8
        with:
          install: sqlclient

      - name: Create Database
        run: sqlcmd -S "${{ steps.tf-outputs.outputs.beanbd_db_address }},${{ steps.tf-outputs.outputs.beanbd_db_port }}" -U "${{ vars.DB_USERNAME }}" -P "${{ secrets.DB_PASSWORD }}" -d master -Q "IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'beanbd_db') BEGIN CREATE DATABASE beanbd_db; END;" -C
      
      - name: Flyway validate and migrate
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:sqlserver://${{ steps.tf-outputs.outputs.beanbd_db_endpoint }};encrypt=true;databaseName=beanbd_db;trustServerCertificate=true;
          user: ${{ vars.DB_USERNAME }}
          password: ${{ secrets.DB_PASSWORD }}
          locations: filesystem:./migrations
        env:
          FLYWAY_VALIDATE_MIGRATION_NAMING: true
 
